# Generated by Django 4.2.23 on 2025-06-14 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_nivel', models.IntegerField()),
                ('tipo_supl1', models.IntegerField()),
                ('supl1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_supl2', models.IntegerField()),
                ('supl2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_supl3', models.IntegerField()),
                ('supl3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_supl4', models.IntegerField()),
                ('supl4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_supl6', models.IntegerField()),
                ('supl6', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_supl8', models.IntegerField()),
                ('supl8', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supl12', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_supl12', models.IntegerField()),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('cuil', models.CharField(max_length=20)),
                ('numero_cuenta', models.CharField(max_length=20)),
                ('situacion', models.CharField(max_length=1)),
                ('estado', models.CharField(max_length=1)),
                ('fecha_ingreso', models.DateField()),
                ('antiguedad', models.IntegerField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, to='empleados.categoria')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='NivelBasico',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.PositiveIntegerField(unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'nivel_basico',
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id_oficina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'oficinas',
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id_titulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_resolucion', models.DateField()),
            ],
            options={
                'db_table': 'titulos',
            },
        ),
        migrations.CreateModel(
            name='Preliquidacion',
            fields=[
                ('id_preliquidacion', models.AutoField(primary_key=True, serialize=False)),
                ('año', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField()),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_por_titulos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, to='empleados.categoria')),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
            options={
                'db_table': 'preliquidacion',
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id_liquidacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_liquidacion', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preliquidacion', models.OneToOneField(db_column='id_preliquidacion', on_delete=django.db.models.deletion.CASCADE, to='empleados.preliquidacion')),
            ],
            options={
                'db_table': 'liquidacion',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='oficina',
            field=models.ForeignKey(db_column='id_oficina', on_delete=django.db.models.deletion.PROTECT, to='empleados.oficina'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='titulo',
            field=models.ForeignKey(db_column='id_titulo', on_delete=django.db.models.deletion.PROTECT, to='empleados.titulo'),
        ),
    ]
