# Generated by Django 4.2.23 on 2025-06-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('id_usuario', models.IntegerField()),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'calificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTitulo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_titulos',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='titulo',
            options={'managed': False},
        ),
    ]
