# Generated by Django 4.2.23 on 2025-06-15 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_calificacion_tipotitulo_alter_titulo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='antiguedad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.categoria'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='oficina',
            field=models.ForeignKey(db_column='id_oficina', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.oficina'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='titulo',
            field=models.ForeignKey(db_column='id_titulo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.titulo'),
        ),
    ]
