# Generated by Django 4.2.23 on 2025-06-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_empleado_antiguedad_alter_empleado_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={},
        ),
    ]
