# Generated by Django 4.2.23 on 2025-06-15 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_calificacion_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preliquidacion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='empleado',
            field=models.ForeignKey(db_column='id_empleado', default=1, on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado'),
            preserve_default=False,
        ),
    ]
