# Generated by Django 4.2.23 on 2025-06-16 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_remove_preliquidacion_fecha_calificacion_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion',
            name='fecha_liquidacion',
        ),
        migrations.RemoveField(
            model_name='liquidacion',
            name='preliquidacion',
        ),
        migrations.RemoveField(
            model_name='liquidacion',
            name='total',
        ),
        migrations.RemoveField(
            model_name='preliquidacion',
            name='salario_base',
        ),
        migrations.RemoveField(
            model_name='preliquidacion',
            name='total_por_titulos',
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='antiguedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='año',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='basico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', default=1, on_delete=django.db.models.deletion.PROTECT, to='empleados.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='categoria_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='empleado',
            field=models.ForeignKey(db_column='id_empleado', default=1, on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='jubilacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='mes',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='nivel',
            field=models.ForeignKey(blank=True, db_column='id_nivel', null=True, on_delete=django.db.models.deletion.PROTECT, to='empleados.nivelbasico'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='obra_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='oficina',
            field=models.ForeignKey(blank=True, db_column='id_oficina', null=True, on_delete=django.db.models.deletion.PROTECT, to='empleados.oficina'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='oficina_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='situacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='supl1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='supl12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='supl2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='supl3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='supl4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='supl6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='supl8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='titulo',
            field=models.ForeignKey(blank=True, db_column='id_titulo', null=True, on_delete=django.db.models.deletion.PROTECT, to='empleados.titulo'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='titulo_completo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='antiguedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='basico',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='categoria_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='jubilacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='nivel',
            field=models.ForeignKey(blank=True, db_column='id_nivel', null=True, on_delete=django.db.models.deletion.PROTECT, to='empleados.nivelbasico'),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='obra_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='oficina',
            field=models.ForeignKey(blank=True, db_column='id_oficina', null=True, on_delete=django.db.models.deletion.PROTECT, to='empleados.oficina'),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='oficina_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='situacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='supl1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='supl12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='supl2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='supl3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='supl4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='supl6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='supl8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='titulo',
            field=models.ForeignKey(blank=True, db_column='id_titulo', null=True, on_delete=django.db.models.deletion.PROTECT, to='empleados.titulo'),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='titulo_completo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
