# Generated by Django 4.2.23 on 2025-06-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_remove_liquidacion_fecha_liquidacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelbasico',
            name='nivel',
            field=models.DecimalField(db_column='monto', decimal_places=2, max_digits=10, unique=True),
        ),
    ]
