# Generated by Django 4.2.23 on 2025-06-18 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleados', '0009_align_categoria_schema'),
    ]

    operations = [
    migrations.AlterModelOptions(
        name='nivelbasico',
        options={'verbose_name': 'Nivel básico', 'verbose_name_plural': 'Niveles básicos'},
    ),

    # — COMENTAMOS TODO LO RELACIONADO CON categoria (no queremos borrarlo ni añadirlo) —
    # migrations.RemoveField(
    #     model_name='categoria',
    #     name='id_nivel',
    # ),
    # migrations.RemoveField(
    #     model_name='categoria',
    #     name='supl1',
    # ),
    # migrations.RemoveField(
    #     model_name='categoria',
    #     name='supl12',
    # ),
    # migrations.RemoveField(
    #     model_name='categoria',
    #     name='supl2',
    # ),
    # migrations.RemoveField(
    #     model_name='categoria',
    #     name='supl3',
    # ),
    # migrations.RemoveField(
    #     model_name='categoria',
    #     name='supl4',
    # ),
    # migrations.RemoveField(
    #     model_name='categoria',
    #     name='supl6',
    # ),
    # migrations.RemoveField(
    #     model_name='categoria',
    #     name='supl8',
    # ),
    # migrations.RemoveField(
    #     model_name='categoria',
    #     name='tipo_supl1',
    # ),
    # migrations.RemoveField(
    #     model_name='categoria',
    #     name='tipo_supl12',
    # ),
    # migrations.RemoveField(
    #     model_name='categoria',
    #     name='tipo_supl2',
    # ),
    # migrations.RemoveField(
    #     model_name='categoria',
    #     name='tipo_supl3',
    # ),
    # migrations.RemoveField(
    #     model_name='categoria',
    #     name='tipo_supl4',
    # ),
    # migrations.RemoveField(
    #     model_name='categoria',
    #     name='tipo_supl6',
    # ),
    # migrations.RemoveField(
    #     model_name='categoria',
    #     name='tipo_supl8',
    # ),

    # migrations.AddField(
    #     model_name='categoria',
    #     name='nivel',
    #     field=models.ForeignKey(blank=True, db_column='id_nivel', null=True, on_delete=django.db.models.deletion.PROTECT, to='empleados.nivelbasico'),
    # ),
    # migrations.AddField(
    #     model_name='categoria',
    #     name='sup1',
    #     field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
    # ),
    # migrations.AddField(
    #     model_name='categoria',
    #     name='sup12',
    #     field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
    # ),
    # migrations.AddField(
    #     model_name='categoria',
    #     name='sup2',
    #     field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
    # ),
    # migrations.AddField(
    #     model_name='categoria',
    #     name='sup3',
    #     field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
    # ),
    # migrations.AddField(
    #     model_name='categoria',
    #     name='sup4',
    #     field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
    # ),
    # migrations.AddField(
    #     model_name='categoria',
    #     name='sup6',
    #     field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
    # ),
    # migrations.AddField(
    #     model_name='categoria',
    #     name='sup8',
    #     field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
    # ),
    # migrations.AddField(
    #     model_name='categoria',
    #     name='tipo_sup1',
    #     field=models.IntegerField(blank=True, db_column='tipo_sup1', null=True),
    # ),
    # migrations.AddField(
    #     model_name='categoria',
    #     name='tipo_sup12',
    #     field=models.IntegerField(blank=True, db_column='tipo_sup12', null=True),
    # ),
    # migrations.AddField(
    #     model_name='categoria',
    #     name='tipo_sup2',
    #     field=models.IntegerField(blank=True, db_column='tipo_sup2', null=True),
    # ),
    # migrations.AddField(
    #     model_name='categoria',
    #     name='tipo_sup3',
    #     field=models.IntegerField(blank=True, db_column='tipo_sup3', null=True),
    # ),
    # migrations.AddField(
    #     model_name='categoria',
    #     name='tipo_sup4',
    #     field=models.IntegerField(blank=True, db_column='tipo_sup4', null=True),
    # ),
    # migrations.AddField(
    #     model_name='categoria',
    #     name='tipo_sup6',
    #     field=models.IntegerField(blank=True, db_column='tipo_sup6', null=True),
    # ),
    # migrations.AddField(
    #     model_name='categoria',
    #     name='tipo_sup8',
    #     field=models.IntegerField(blank=True, db_column='tipo_sup8', null=True),
    # ),

    # — Estas sí se aplican —
    migrations.AlterField(
        model_name='calificacion',
        name='id_usuario',
        field=models.ForeignKey(
            blank=True,
            db_column='id_usuario',
            null=True,
            on_delete=django.db.models.deletion.PROTECT,
            to=settings.AUTH_USER_MODEL,
            verbose_name='Usuario que registra'
        ),
    ),
    migrations.AlterField(
        model_name='calificacion',
        name='mes',
        field=models.PositiveSmallIntegerField(
            choices=[(i, i) for i in range(1, 13)]
        ),
    ),
    migrations.AlterField(
        model_name='categoria',
        name='id_categoria',
        field=models.AutoField(primary_key=True, serialize=False),
    ),
    migrations.AlterField(
        model_name='nivelbasico',
        name='descripcion',
        field=models.CharField(blank=True, max_length=100, verbose_name='Descripción'),
    ),
    migrations.AlterField(
        model_name='preliquidacion',
        name='categoria_nombre',
        field=models.TextField(blank=True, null=True),
    ),
    migrations.AlterField(
        model_name='preliquidacion',
        name='oficina_nombre',
        field=models.TextField(blank=True, null=True),
    ),
    migrations.AlterField(
        model_name='preliquidacion',
        name='titulo_completo',
        field=models.TextField(blank=True, null=True),
    ),
]
