# Generated by Django 5.2.3 on 2025-06-25 15:56

import django.db.models.deletion
from django.db import migrations, models


# Generated by Django on 2025-06-25
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('empleados',
         '0010_alter_nivelbasico_options_remove_categoria_id_nivel_and_more'),
    ]

    operations = [
        # — Estos AddField ya están en la tabla, los comentamos para no duplicar columnas —
        # migrations.AddField(
        #     model_name='categoria',
        #     name='sup1',
        #     field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        # ),
        # migrations.AddField(
        #     model_name='categoria',
        #     name='sup12',
        #     field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        # ),
        # migrations.AddField(
        #     model_name='categoria',
        #     name='sup2',
        #     field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        # ),
        # migrations.AddField(
        #     model_name='categoria',
        #     name='sup3',
        #     field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        # ),
        # migrations.AddField(
        #     model_name='categoria',
        #     name='sup4',
        #     field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        # ),
        # migrations.AddField(
        #     model_name='categoria',
        #     name='sup6',
        #     field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        # ),
        # migrations.AddField(
        #     model_name='categoria',
        #     name='sup8',
        #     field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        # ),
        # migrations.AddField(
        #     model_name='categoria',
        #     name='tipo_sup1',
        #     field=models.IntegerField(blank=True, db_column='tipo_sup1', null=True),
        # ),
        # migrations.AddField(
        #     model_name='categoria',
        #     name='tipo_sup12',
        #     field=models.IntegerField(blank=True, db_column='tipo_sup12', null=True),
        # ),
        # migrations.AddField(
        #     model_name='categoria',
        #     name='tipo_sup2',
        #     field=models.IntegerField(blank=True, db_column='tipo_sup2', null=True),
        # ),
        # migrations.AddField(
        #     model_name='categoria',
        #     name='tipo_sup3',
        #     field=models.IntegerField(blank=True, db_column='tipo_sup3', null=True),
        # ),
        # migrations.AddField(
        #     model_name='categoria',
        #     name='tipo_sup4',
        #     field=models.IntegerField(blank=True, db_column='tipo_sup4', null=True),
        # ),
        # migrations.AddField(
        #     model_name='categoria',
        #     name='tipo_sup6',
        #     field=models.IntegerField(blank=True, db_column='tipo_sup6', null=True),
        # ),
        # migrations.AddField(
        #     model_name='categoria',
        #     name='tipo_sup8',
        #     field=models.IntegerField(blank=True, db_column='tipo_sup8', null=True),
        # ),

        # — Mantenemos sólo los AlterField que realmente cambian metadatos o límites —
        migrations.AlterField(
            model_name='liquidacion',
            name='antiguedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='año',
            field=models.PositiveSmallIntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='categoria_nombre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='mes',
            field=models.PositiveSmallIntegerField(choices=[(i, i) for i in range(1, 13)], verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='oficina_nombre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='situacion',
            field=models.CharField(blank=True,
                choices=[('C', 'Contratado'), ('P', 'Permanente')],
                max_length=1, null=True, verbose_name='Situación'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='supl12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='titulo_completo',
            field=models.TextField(blank=True, null=True),
        ),

        migrations.AlterField(
            model_name='preliquidacion',
            name='antiguedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='preliquidacion',
            name='año',
            field=models.PositiveSmallIntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='preliquidacion',
            name='mes',
            field=models.PositiveSmallIntegerField(choices=[(i, i) for i in range(1, 13)], verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='preliquidacion',
            name='situacion',
            field=models.CharField(blank=True,
                choices=[('C', 'Contratado'), ('P', 'Permanente')],
                max_length=1, null=True, verbose_name='Situación'),
        ),
        migrations.AlterField(
            model_name='preliquidacion',
            name='supl12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='preliquidacion',
            name='supl4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]