# Generated by Django 5.2.3 on 2025-06-25 15:56
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0011_alter_liquidacion_options_and_more'),
    ]

    operations = [
        # ———————— Sólo AlterField, nada de AddField ————————

        # Ampliamos los suplementos en Liquidacion a 12,2
        migrations.AlterField(
            model_name='liquidacion',
            name='supl1',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='supl2',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='supl3',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='supl4',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='supl6',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='supl8',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True),
        ),

        # Ampliamos los suplementos en Preliquidacion a 12,2
        migrations.AlterField(
            model_name='preliquidacion',
            name='supl1',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='preliquidacion',
            name='supl2',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='preliquidacion',
            name='supl3',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='preliquidacion',
            name='supl4',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='preliquidacion',
            name='supl6',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='preliquidacion',
            name='supl8',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True),
        ),
    ]
