# Generated by Django 5.2.3 on 2025-07-01 04:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0012_alter_liquidacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidacion',
            options={'verbose_name': 'Liquidación', 'verbose_name_plural': 'Liquidaciones'},
        ),
        migrations.AlterModelOptions(
            name='preliquidacion',
            options={'verbose_name': 'Preliquidación', 'verbose_name_plural': 'Preliquidaciones'},
        ),
       
        migrations.AddField(
            model_name='liquidacion',
            name='oficio_descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Descuento Judicial'),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='oficio_descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Descuento Judicial'),
        ),
        migrations.CreateModel(
            name='OficioJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Mes')),
                ('monto_descontar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto a Descontar')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado', verbose_name='Usuario (Empleado)')),
            ],
            options={
                'verbose_name': 'Oficio Judicial',
                'verbose_name_plural': 'Oficios Judiciales',
                'ordering': ['-anio', '-mes', 'empleado__apellido'],
                'unique_together': {('anio', 'mes', 'empleado')},
            },
        ),
    ]
