# Generated by Django 5.2.3 on 2025-07-01 05:00

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0013_alter_liquidacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nivel',
            field=models.ForeignKey(
                to='empleados.NivelBasico',
                on_delete=django.db.models.deletion.PROTECT,
                db_column='id_nivel',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='categoria',
            name='sup1',
            field=models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='sup2',
            field=models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='sup3',
            field=models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='sup4',
            field=models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='sup6',
            field=models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='sup8',
            field=models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='sup12',
            field=models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_sup1',
            field=models.IntegerField(db_column='tipo_sup1', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_sup2',
            field=models.IntegerField(db_column='tipo_sup2', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_sup3',
            field=models.IntegerField(db_column='tipo_sup3', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_sup4',
            field=models.IntegerField(db_column='tipo_sup4', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_sup6',
            field=models.IntegerField(db_column='tipo_sup6', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_sup8',
            field=models.IntegerField(db_column='tipo_sup8', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_sup12',
            field=models.IntegerField(db_column='tipo_sup12', null=True, blank=True),
        ),
    ]
