# Generated by Django 5.2.3 on 2025-07-03 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0013_alter_liquidacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id_nivel',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='supl1',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='supl12',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='supl2',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='supl3',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='supl4',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='supl6',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='supl8',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipo_supl1',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipo_supl12',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipo_supl2',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipo_supl3',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipo_supl4',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipo_supl6',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipo_supl8',
        ),
        migrations.AddField(
            model_name='categoria',
            name='nivel',
            field=models.ForeignKey(blank=True, db_column='id_nivel', null=True, on_delete=django.db.models.deletion.PROTECT, to='empleados.nivelbasico'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='sup1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='sup12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='sup2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='sup3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='sup4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='sup6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='sup8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_sup1',
            field=models.IntegerField(blank=True, db_column='tipo_sup1', null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_sup12',
            field=models.IntegerField(blank=True, db_column='tipo_sup12', null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_sup2',
            field=models.IntegerField(blank=True, db_column='tipo_sup2', null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_sup3',
            field=models.IntegerField(blank=True, db_column='tipo_sup3', null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_sup4',
            field=models.IntegerField(blank=True, db_column='tipo_sup4', null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_sup6',
            field=models.IntegerField(blank=True, db_column='tipo_sup6', null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_sup8',
            field=models.IntegerField(blank=True, db_column='tipo_sup8', null=True),
        ),
        migrations.AddField(
            model_name='preliquidacion',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje'), (2, 'Monto fijo')], default=1, verbose_name='Tipo Descuento'),
        ),
    ]
