# Generated by Django 5.2.3 on 2025-07-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0014_remove_categoria_id_nivel_remove_categoria_supl1_and_more'),
    ]

    operations = [
    ]
