# Generated by Django 5.2.3 on 2025-07-03 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0015_add_tipo_preliquidacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficiojudicial',
            options={},
        ),
        migrations.AddField(
            model_name='oficiojudicial',
            name='porcentaje_descontar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje a descontar'),
        ),
        migrations.AddField(
            model_name='oficiojudicial',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje'), (2, 'Monto fijo')], default=2, verbose_name='Tipo de descuento'),
        ),
        migrations.AlterField(
            model_name='oficiojudicial',
            name='anio',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='oficiojudicial',
            name='empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='oficiojudicial',
            name='mes',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)]),
        ),
        migrations.AlterField(
            model_name='oficiojudicial',
            name='monto_descontar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto a descontar'),
        ),
        migrations.AlterModelTable(
            name='oficiojudicial',
            table='oficio_judicial',
        ),
    ]
