# Generated by Django 5.2.3 on 2025-07-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0016_alter_oficiojudicial_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preliquidacion',
            name='oficio_descuento',
        ),
    ]
