# Generated by Django 5.2.3 on 2025-07-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0017_remove_preliquidacion_oficio_descuento_and_more'),
    ]

    operations = [
    ]
