# Generated by Django 5.2.3 on 2025-07-03 22:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0018_sync_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliquidacion',
            name='oficio_judicial',
            field=models.DecimalField(db_column='oficio_judicial', decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Oficio Judicial'),
        ),
        migrations.AlterField(
            model_name='preliquidacion',
            name='situacion',
            field=models.CharField(blank=True, choices=[('C', 'Contratado'), ('P', 'Permanente')], max_length=1, null=True),
        ),
    ]
