# Generated by Django 5.2.3 on 2025-07-03 22:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0019_preliquidacion_oficio_judicial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion',
            name='oficio_descuento',
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='oficio_judicial',
            field=models.DecimalField(db_column='oficio_judicial', decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Oficio Judicial'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje'), (2, 'Monto fijo')], default=1, verbose_name='Tipo Descuento'),
        ),
    ]
