# Generated by Django 5.2.3 on 2025-07-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0020_remove_liquidacion_oficio_descuento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion',
            name='tipo',
        ),
    ]
