# Generated by Django 5.2.3 on 2025-07-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0021_remove_liquidacion_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preliquidacion',
            name='tipo',
        ),
    ]
