# Generated by Django 5.2.3 on 2025-07-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0022_remove_preliquidacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preliquidacion',
            name='antiguedad',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Años de servicio', null=True),
        ),
        migrations.AlterField(
            model_name='preliquidacion',
            name='bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='preliquidacion',
            name='jubilacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='preliquidacion',
            name='liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='preliquidacion',
            name='obra_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('empleado', 'año', 'mes')},
        ),
    ]
