# Generated by Django 5.2.3 on 2025-07-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0023_alter_preliquidacion_antiguedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='conformada',
            field=models.BooleanField(default=False),
        ),
    ]
