# Generated by Django 5.2.3 on 2025-07-16 15:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0024_liquidacion_conformada'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='basico_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='importe_antiguedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='importe_titulo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='total_descuentos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='total_suplementos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='antiguedad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='jubilacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='obra_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='oficio_judicial',
            field=models.DecimalField(db_column='oficio_judicial', decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Oficio Judicial'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='situacion',
            field=models.CharField(blank=True, choices=[('C', 'Contratado'), ('P', 'Permanente')], max_length=1, null=True),
        ),
    ]
