# Generated by Django on YYYY‑MM‑DD HH:MM
from decimal import Decimal
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0026_alter_liquidacion_basico_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='importe_titulo',
            field=models.DecimalField(
                max_digits=12,
                decimal_places=2,
                default=Decimal('0.00'),
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='importe_antiguedad',
            field=models.DecimalField(
                max_digits=12,
                decimal_places=2,
                default=Decimal('0.00'),
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='basico_total',
            field=models.DecimalField(
                max_digits=12,
                decimal_places=2,
                default=Decimal('0.00'),
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='total_suplementos',
            field=models.DecimalField(
                max_digits=14,
                decimal_places=2,
                default=Decimal('0.00'),
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='total_descuentos',
            field=models.DecimalField(
                max_digits=14,
                decimal_places=2,
                default=Decimal('0.00'),
                null=True,
                blank=True
            ),
        ),
    ]
