# Generated by Django 4.2.23 on 2025-07-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0027_add_missing_liquidacion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='area',
            field=models.CharField(choices=[('PRESIDENCIA', 'Presidencia'), ('SECRET. TÉCNICA CONTABLE', 'Secret. Técnica Contable'), ('PLANES DE EMERGENCIA', 'Planes de Emergencia'), ('SECRETARÍA TEC. SOCIAL', 'Secretaría Tec. Social')], default='PRESIDENCIA', max_length=40),
        ),
    ]
