# Generated by Django 4.2.23 on 2025-08-01 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0028_empleado_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nivel_basico',
            field=models.ForeignKey(db_column='id_nivel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.nivelbasico'),
        ),
    ]
