# Generated by Django 5.2.3 on 2025-08-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0029_empleado_nivel_basico'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='area',
            field=models.CharField(choices=[('PRESIDENCIA', 'Presidencia'), ('SECRET. TÉCNICA CONTABLE', 'Secret. Técnica Contable'), ('PLANES DE EMERGENCIA', 'Planes de Emergencia'), ('SECRETARÍA TEC. SOCIAL', 'Secretaría Tec. Social')], default='PRESIDENCIA', max_length=60),
        ),
    ]
