# Generated by Django 5.2.3 on 2025-08-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0030_categoria_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='sup1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='sup12',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='sup2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='sup3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='sup4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='sup6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='sup8',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_sup1',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje (%)'), (2, 'Monto fijo ($)')], db_column='tipo_sup1', default=1),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_sup12',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje (%)'), (2, 'Monto fijo ($)')], db_column='tipo_sup12', default=2),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_sup2',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje (%)'), (2, 'Monto fijo ($)')], db_column='tipo_sup2', default=1),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_sup3',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje (%)'), (2, 'Monto fijo ($)')], db_column='tipo_sup3', default=1),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_sup4',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje (%)'), (2, 'Monto fijo ($)')], db_column='tipo_sup4', default=1),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_sup6',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje (%)'), (2, 'Monto fijo ($)')], db_column='tipo_sup6', default=2),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_sup8',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje (%)'), (2, 'Monto fijo ($)')], db_column='tipo_sup8', default=1),
        ),
    ]
