# Generated by Django 5.2.1 on 2025-08-20 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0031_alter_categoria_nombre_alter_categoria_sup1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(db_index=True, max_length=7, unique=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('CONFIRMADA', 'Confirmada')], default='ABIERTA', max_length=12)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_cerrada', models.DateTimeField(blank=True, null=True)),
                ('fecha_confirmada', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Liquidación por período',
                'verbose_name_plural': 'Liquidaciones por período',
                'db_table': 'empleados_liquidacion_periodo',
                'ordering': ['-periodo'],
            },
        ),
        migrations.AlterField(
            model_name='oficiojudicial',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monto fijo'), (2, 'Porcentaje')], default=1, verbose_name='Tipo de descuento'),
        ),
        migrations.AddIndex(
            model_name='oficiojudicial',
            index=models.Index(fields=['anio', 'mes', 'empleado'], name='oficio_judi_anio_3454d5_idx'),
        ),
        migrations.AddField(
            model_name='liquidacionperiodo',
            name='abierta_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liqs_abiertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidacionperiodo',
            name='cerrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liqs_cerradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidacionperiodo',
            name='confirmada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liqs_confirmadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
