# Generated by Django 5.2.1 on 2025-09-08 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0032_liquidacionperiodo_alter_oficiojudicial_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ('apellido', 'nombre')},
        ),
        migrations.AlterModelOptions(
            name='oficiojudicial',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveIndex(
            model_name='oficiojudicial',
            name='oficio_judi_anio_3454d5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='oficiojudicial',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='antiguedad',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='empleados.categoria'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cuil',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text='1=Activo / 0=Inactivo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nivel_basico',
            field=models.ForeignKey(db_column='id_nivel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='empleados.nivelbasico'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_cuenta',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='oficina',
            field=models.ForeignKey(db_column='id_oficina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='empleados.oficina'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='situacion',
            field=models.CharField(choices=[('P', 'PERMANENTE'), ('C', 'CONTRATADO')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='titulo',
            field=models.ForeignKey(db_column='id_titulo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='empleados.titulo'),
        ),
        migrations.AlterField(
            model_name='oficiojudicial',
            name='empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, related_name='oficios_judiciales', to='empleados.empleado'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['estado', 'fecha_salida'], name='empleados_estado_eb2ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['cuil'], name='empleados_cuil_51a4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['dni'], name='empleados_dni_ecb314_idx'),
        ),
        migrations.AddIndex(
            model_name='oficiojudicial',
            index=models.Index(fields=['empleado', 'anio', 'mes'], name='oficio_judi_id_empl_f21705_idx'),
        ),
    ]
