# Generated by Django 5.2.1 on 2025-09-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0033_alter_empleado_options_alter_oficiojudicial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preliquidacion',
            name='antiguedad',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Años de servicio (calculado por período con regla IPVU)', null=True),
        ),
    ]
