# Generated by Django 5.2.1 on 2025-09-18 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0034_alter_preliquidacion_antiguedad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(db_index=True, max_length=7)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipo', models.CharField(choices=[('EMPLEADO_ALTA', 'Alta de empleado'), ('EMPLEADO_BAJA', 'Baja de empleado'), ('CAMBIO_CATEG', 'Cambio de categoría'), ('CAMBIO_CALIF', 'Cambio de calificación'), ('OFICIO_CREADO', 'Oficio judicial creado'), ('PRELIQ_GENERADA', 'Preliquidación generada'), ('OTRO', 'Otro')], max_length=32)),
                ('descripcion', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_realizadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='empleados.empleado')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['periodo', 'tipo'], name='empleados_n_periodo_69c504_idx'), models.Index(fields=['fecha'], name='empleados_n_fecha_8bd6de_idx')],
            },
        ),
    ]
