# Generated by Django 5.2.1 on 2025-09-21 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0035_novedadmensual'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='novedadmensual',
            name='empleados_n_periodo_69c504_idx',
        ),
        migrations.RemoveIndex(
            model_name='novedadmensual',
            name='empleados_n_fecha_8bd6de_idx',
        ),
        migrations.AlterModelTable(
            name='novedadmensual',
            table='empleados_novedadmensual',
        ),
    ]
