# Generated by Django 5.2.1 on 2025-09-29 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0036_remove_novedadmensual_empleados_n_periodo_69c504_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='nivelbasico',
            options={'managed': False, 'ordering': ['id_nivel'], 'verbose_name': 'Nivel básico', 'verbose_name_plural': 'Niveles básicos'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nivel',
            field=models.ForeignKey(blank=True, db_column='id_nivel', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='empleados.nivelbasico', verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_sup1',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje (%)'), (2, 'Monto fijo ($)')], default=1),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_sup12',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje (%)'), (2, 'Monto fijo ($)')], default=2),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_sup2',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje (%)'), (2, 'Monto fijo ($)')], default=1),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_sup3',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje (%)'), (2, 'Monto fijo ($)')], default=1),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_sup4',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje (%)'), (2, 'Monto fijo ($)')], default=1),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_sup6',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje (%)'), (2, 'Monto fijo ($)')], default=2),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_sup8',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje (%)'), (2, 'Monto fijo ($)')], default=1),
        ),
    ]
