# Generated by Django 5.2.1 on 2025-09-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0037_alter_categoria_options_alter_nivelbasico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='basico_manual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto básico personalizado (solo si no se usa un nivel predefinido)', max_digits=12, null=True, verbose_name='Básico manual'),
        ),
    ]
