# Generated by Django 5.2.1 on 2025-10-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0038_categoria_basico_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
