# Generated by Django 5.2.1 on 2025-10-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0039_alter_oficina_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (0, 'Inactivo'), (2, 'Retención de Cargo')], db_index=True, default=1, verbose_name='Estado'),
        ),
    ]
