# Generated by Django 5.2.1 on 2025-10-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0040_alter_empleado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.CharField(default='PRESIDENCIA', editable=False, max_length=40, verbose_name='Área'),
        ),
    ]
