# Generated by Django 5.2.1 on 2025-10-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0041_alter_empleado_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficiojudicial',
            name='codigo_mutual',
            field=models.CharField(default='001', help_text='Código de 3 dígitos (ej: 001=AMUR, 048=Préstamos, 123=Seguros)', max_length=3, verbose_name='Código mutual/servicio'),
        ),
        migrations.AddField(
            model_name='oficiojudicial',
            name='novedad',
            field=models.CharField(choices=[('D', 'Descuento activo'), ('A', 'Alta nueva'), ('B', 'Baja/Cancelación')], default='D', help_text='D=Descuento activo, A=Alta nueva, B=Baja', max_length=1, verbose_name='Tipo de novedad'),
        ),
        migrations.AddField(
            model_name='oficiojudicial',
            name='numero_cuota',
            field=models.PositiveSmallIntegerField(default=1, help_text='Cuota actual (ej: 4 de 12). Si es descuento fijo mensual, dejar en 1', verbose_name='Número de cuota'),
        ),
    ]
