# Generated by Django 5.2.1 on 2025-11-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0042_oficiojudicial_codigo_mutual_oficiojudicial_novedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedadmensual',
            name='tipo',
            field=models.CharField(choices=[('EMPLEADO_ALTA', 'Alta de empleado'), ('EMPLEADO_BAJA', 'Baja de empleado'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('CAMBIO_CATEG', 'Cambio de categoría'), ('CAMBIO_CALIF', 'Cambio de calificación'), ('OFICIO_CREADO', 'Oficio judicial creado'), ('PRELIQ_GENERADA', 'Preliquidación generada'), ('OTRO', 'Otro')], max_length=32),
        ),
    ]
